In [8]:
import pandas as pd
from config.config import OUTPUT_FILE, OUTPUT_CSV_FILE

df = pd.read_json(OUTPUT_FILE)
df

df.to_csv(OUTPUT_CSV_FILE)
df

,item_id,amount,currency,location,Kateqoriya,Sahə,Təmir,Mərtəbə,Otaq sayı,Çıxarış,Torpaq sahəsi,İpoteka
0,5056827,5000,AZN,"[Rəssamlıq Akademiyası, Nəriman Nərimanov m., ...",Obyekt,500 m²,var,NaN,NaN,NaN,NaN,NaN
1,4959734,310000,AZN,[],Yeni tikili,150 m²,var,6 / 14,4.0,var,NaN,NaN
2,5142259,300000,AZN,"[Memar Əcəmi m., Binəqədi r.]",Obyekt,50 m²,var,NaN,NaN,var,NaN,NaN
3,5165167,340000,AZN,"[Xəzər r., Şüvəlan q.]",Həyət evi/Bağ evi,250 m²,var,NaN,5.0,var,6 sot,NaN
4,5122759,220000,AZN,"[Azadlıq Prospekti m., Binəqədi r., 8-ci mikro...",Köhnə tikili,85 m²,var,2 / 9,3.0,var,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
79,5140712,131000,AZN,"[Abşeron r., Novxanı q.]",Həyət evi/Bağ evi,200 m²,var,NaN,5.0,var,4.8 sot,var
80,5149053,435000,AZN,[Sabunçu r.],Yeni tikili,133.4 m²,yoxdur,4 / 6,3.0,yoxdur,NaN,var
81,5161334,105000,AZN,"[Suraxanı r., Hövsan q.]",Yeni tikili,90 m²,var,9 / 12,3.0,var,NaN,var
82,5038503,151000,AZN,"[20 Yanvar m., Yasamal r.]",Yeni tikili,52 m²,var,10 / 18,2.0,var,NaN,var
83,5126935,125000,AZN,"[Abşeron r., Novxanı q.]",Həyət evi/Bağ evi,210 m²,var,NaN,5.0,var,11 sot,NaN