In [1]:
import pandas as pd
from config.config import OUTPUT_FILE, OUTPUT_CSV_FILE

df = pd.read_json(OUTPUT_FILE)
df

df.to_csv(OUTPUT_CSV_FILE)
df

,item_id,amount,currency,location,Kateqoriya,Sahə,Torpaq sahəsi,Otaq sayı,Çıxarış,İpoteka,Təmir,Mərtəbə,Binanın növü
0,4732723,660000,AZN,"[Xəzər r., Mərdəkan q.]",Həyət evi/Bağ evi,240 m²,8 sot,4.0,var,var,var,NaN,NaN
1,2713423,750000,AZN,"[Xəzər r., Mərdəkan q.]",Həyət evi/Bağ evi,500 m²,10 sot,NaN,var,NaN,var,NaN,NaN
2,4823403,225000,AZN,"[Xəzər r., Şüvəlan q.]",Həyət evi/Bağ evi,150 m²,4 sot,4.0,var,var,var,NaN,NaN
3,5184339,150000,AZN,"[Gənclik m., Respublika stadionu, Azərbaycan t...",Köhnə tikili,50 m²,NaN,2.0,var,NaN,var,4 / 5,NaN
4,5156987,150000,AZN,"[Abşeron r., Mehdiabad q.]",Həyət evi/Bağ evi,100 m²,6 sot,3.0,var,NaN,var,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2676,5192367,3200,AZN,[],Torpaq,3 sot,NaN,NaN,var,NaN,NaN,NaN,NaN
2677,4775715,260000,AZN,"[Xəzər r., Şüvəlan q.]",Həyət evi/Bağ evi,180 m²,4 sot,4.0,var,var,var,NaN,NaN
2678,5161778,1500,AZN,"[Hüseyn Cavid parkı, Elmlər Akademiyası m., Te...",Yeni tikili,100 m²,NaN,3.0,NaN,NaN,var,10 / 16,NaN
2679,5192310,2000,AZN,"[Xətai r., Ağ şəhər q., Ağ şəhər]",Yeni tikili,65 m²,NaN,2.0,NaN,NaN,var,6 / 20,NaN
2680,5146878,2750000,AZN,[],Torpaq,81 sot,NaN,NaN,var,NaN,NaN,NaN,NaN